export default {
  LOGIN_FAILED: 102,
  INTERNAL_SERVER_ERROR: 103,
  INVALID_SYNTAX: 104,
  DUPILICATE_EMAIL: 108,
  UNAUTHORIZED_DELETE_OTHER_ADMIN: 113,
  UNAUTHORIZED_EDIT_OTHER_ADMIN: 114,
  RESOURCE_NOT_EXIST: 115,
};
