export default {
  LOGIN_FAILED: 102,
  INTERNAL_SERVER_ERROR: 103,
  INVALID_SYNTAX: 104,
  DUPLICATE_EMAIL: 108,
  INVALID_USER: 112,
  UNAUTHORIZED_DELETE_OTHER_ADMIN: 113,
  UNAUTHORIZED_EDIT_OTHER_ADMIN: 114,
  RESOURCE_NOT_EXIST: 115,
  REQUIRED_TOKEN: 116,
  LOGIC_SYNTAX_ERROR: 117,
  INSUFFICIENT_RESOURCES_ERROR: 118,
  NETWORK_CONNECTION_ERROR: 119,
};
